puts "Desarrollador 1 modificando test.rb"
puts "Feature 1"
puts "Feature 2 / Mensajería entre usuarios del pago movil"
puts "Aki"
puts "denis"
puts "gustavo"
puts "Judith Zamphiropolos"
puts "Hugo Ruffinelli"
puts "Judith"
puts "gustavo01"
